In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('data_final.csv',encoding='cp949')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347299 entries, 0 to 347298
Data columns (total 45 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   기준년월         347299 non-null  int64
 1   업종_대분류       347299 non-null  object
 2   업종_중분류       347299 non-null  object
 3   사업장_시도       330306 non-null  object
 4   사업장_시군구      330091 non-null  object
 5   법인_고객등급      347299 non-null  object
 6   전담고객여부       347299 non-null  object
 7   요구불예금잔액      347299 non-null  float64
 8   거치식예금잔액      347299 non-null  float64
 9   적립식예금잔액      347299 non-null  float64
 10  수익증권잔액       347299 non-null  float64
 11  신탁잔액         347299 non-null  float64
 12  퇴직연금잔액       347299 non-null  float64
 13  여신한도금액       347299 non-null  float64
 14  여신_운전자금대출잔액  347299 non-null  float64
 15  여신_시설자금대출잔액  347299 non-null  float64
 16  외환_수출실적금액    347299 non-null  float64
 17  외환_수입실적금액    347299 non-null  float64
 18  신용카드사용금액     347299 non-null  float64
 19  체크카드사용금액     347299 non-null  float64
 20  창구거래금액       347299 non-null  float64
 21  인터넷뱅킹거래금액    347299 non-null  float64
 22  스마트뱅킹거래금액    347299 non-null  float64
 23  폰뱅킹거래금액      347299 non-null  float64
 24  ATM거래금액      347299 non-null  float64
 25  자동이체금액       347299 non-null  float64
 26  요구불입금금액      347299 non-null  float64
 27  요구불출금금액      347299 non-null  float64
 28  요구불예금좌수      347299 non-null  object
 29  거치식예금좌수      347299 non-null  object
 30  적립식예금좌수      347299 non-null  object
 31  수익증권좌수       347299 non-null  object
 32  신탁좌수         347299 non-null  object
 33  퇴직연금좌수       347299 non-null  object
 34  여신_운전자금대출좌수  347299 non-null  object
 35  여신_시설자금대출좌수  347299 non-null  object
 36  신용카드개수       347299 non-null  object
 37  외환_수출실적거래건수  347299 non-null  object
 38  외환_수입실적거래건수  347299 non-null  object
 39  창구거래건수       347299 non-null  object
 40  인터넷뱅킹거래건수    347299 non-null  object
 41  스마트뱅킹거래건수    347299 non-null  object
 42  폰뱅킹거래건수      347299 non-null  object
 43  ATM거래건수      347299 non-null  object
 44  자동이체거래건수     347299 non-null  object
dtypes: float64(21), int64(1), object(23)
memory usage: 119.2+ MB

In [4]:
data_daegu = data[data["사업장_시도"].str.contains("대구", na=False)]
data_daegu

,기준년월,업종_대분류,업종_중분류,사업장_시도,사업장_시군구,법인_고객등급,전담고객여부,요구불예금잔액,거치식예금잔액,적립식예금잔액,...,여신_시설자금대출좌수,신용카드개수,외환_수출실적거래건수,외환_수입실적거래건수,창구거래건수,인터넷뱅킹거래건수,스마트뱅킹거래건수,폰뱅킹거래건수,ATM거래건수,자동이체거래건수
0,202412,건설업,종합 건설업,대구광역시,서구,일반,N,0.16,0.0,0.0,...,0개,10개초과 20개이하,0건,0건,0건,0건,2건초과 5건이하,0건,0건,10건초과 20건이하
1,202412,건설업,종합 건설업,대구광역시,서구,일반,N,0.03,0.0,0.0,...,0개,0개,0건,0건,0건,0건,0건,0건,0건,0건
3,202412,건설업,종합 건설업,대구광역시,서구,우수,Y,180.00,0.0,0.0,...,0개,0개,0건,0건,2건초과 5건이하,20건초과 30건이하,0건,0건,0건,5건초과 10건이하
4,202412,건설업,종합 건설업,대구광역시,서구,우수,Y,41.00,0.0,0.0,...,0개,5개초과 10개이하,0건,0건,1건,10건초과 20건이하,0건,0건,0건,20건초과 30건이하
6,202412,건설업,종합 건설업,대구광역시,서구,최우수,N,2.80,0.0,0.0,...,0개,2개초과 5개이하,0건,0건,0건,50건 초과,0건,0건,2건초과 5건이하,10건초과 20건이하
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347285,202203,부동산업,부동산업,대구광역시,수성구,일반,Y,1.40,0.0,0.0,...,2개,1개,0건,0건,0건,0건,0건,0건,0건,2건초과 5건이하
347288,202203,제조업,전기장비 제조업,대구광역시,서구,일반,N,0.81,0.0,0.0,...,0개,5개초과 10개이하,0건,0건,0건,0건,0건,0건,0건,10건초과 20건이하
347289,202203,제조업,기타 제품 제조업,대구광역시,북구,일반,N,0.43,0.0,0.0,...,0개,0개,0건,0건,0건,10건초과 20건이하,0건,0건,0건,2건초과 5건이하
347294,202203,제조업,금속가공제품 제조업; 기계 및 가구 제외,대구광역시,북구,일반,N,0.02,0.0,0.0,...,0개,0개,0건,0건,0건,1건,0건,0건,2건,0건
347295,202203,정보통신업,"컴퓨터 프로그래밍, 시스템 통합 및 관리업",대구광역시,중구,일반,N,0.01,0.0,0.0,...,0개,0개,0건,0건,2건초과 5건이하,0건,0건,0건,2건,1건